package gui;

import java.awt.Font;

public class JanelaAjuda extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/** Creates new form JanelaAjuda */
    public JanelaAjuda(String title, String text) {
    	super(title);
        initComponents(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String text) {
    	    	 	
        jScrollPane1 = new javax.swing.JScrollPane();
        areaAjuda = new javax.swing.JTextArea();

        areaAjuda.setColumns(20);
        areaAjuda.setRows(5);
        areaAjuda.setText(text);
        areaAjuda.setEditable(false);
        areaAjuda.setFont(new Font("Monospaced", 0, 12));
        jScrollPane1.setViewportView(areaAjuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        
        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JTextArea areaAjuda;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration

}
