package gui;

import java.net.URL;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

import org.prevayler.Prevayler;
import org.prevayler.TransactionWithQuery;

import de.preclipse.bo.*;

public class PainelInserirCurso extends JPanel {

	private static final long serialVersionUID = 1L;

	public PainelInserirCurso(Prevayler prevayler) {
		this.prevayler = prevayler;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		labelTitulo = new javax.swing.JLabel();
		labelCodigo = new javax.swing.JLabel();
		labelNome = new javax.swing.JLabel();
		fieldCodigo = new javax.swing.JTextField();
		fieldNome = new javax.swing.JTextField();
		labelCapacidade = new javax.swing.JLabel();
		
		String pathFigure = "/gui/imagens/ajuda.png";
		URL url = this.getClass().getResource(pathFigure);
		Icon icone = new ImageIcon(url);
		buttonHelp = new JButton("",icone);
		buttonHelp.setContentAreaFilled(false);
		buttonHelp.setBorderPainted(false);
		
		buttonInserir = new javax.swing.JButton();
		buttonLimpar = new javax.swing.JButton();
		labelLogo = new javax.swing.JLabel();
		radioTurno1 = new javax.swing.JRadioButton();
		radioTurno2 = new javax.swing.JRadioButton();

		jPanel1.setPreferredSize(new java.awt.Dimension(531, 544));

		labelTitulo.setFont(new java.awt.Font("Dialog", 0, 24));
		labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelTitulo.setText("Inserir Curso");

		labelCodigo.setText("Codigo");

		labelNome.setText("Nome");

		labelCapacidade.setText("Turno");

		buttonHelp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonHelpActionPerformed(evt);
			}
		});

		buttonInserir.setText("Inserir");
		buttonInserir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonInserirActionPerformed(evt);
			}
		});

		buttonLimpar.setText("Limpar");
		buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonLimparActionPerformed(evt);
			}
		});

		buttonGroup1.add(radioTurno1);
		radioTurno1.setSelected(true);
		radioTurno1.setText("1");

		buttonGroup1.add(radioTurno2);
		radioTurno2.setText("2");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
										.addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
										.addGap(18, 18, 18)
										.addComponent(buttonHelp))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
												.addGap(170, 170, 170)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGap(23, 23, 23)
																.addComponent(labelCodigo)
																.addGap(18, 18, 18)
																.addComponent(fieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addGap(29, 29, 29)
																		.addComponent(labelCapacidade)
																		.addGap(18, 18, 18)
																		.addComponent(radioTurno1)
																		.addGap(18, 18, 18)
																		.addComponent(radioTurno2))))
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addGap(160, 160, 160)
																				.addComponent(buttonInserir)
																				.addGap(18, 18, 18)
																				.addComponent(buttonLimpar))
																				.addGroup(jPanel1Layout.createSequentialGroup()
																						.addGap(178, 178, 178)
																						.addComponent(labelTitulo))
																						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																								.addGap(199, 199, 199)
																								.addComponent(labelNome)
																								.addGap(18, 18, 18)
																								.addComponent(fieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
																								.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(labelTitulo)
						.addGap(62, 62, 62)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(fieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelCodigo))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(labelNome))
										.addGap(18, 18, 18)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(labelCapacidade)
												.addComponent(radioTurno1)
												.addComponent(radioTurno2))
												.addGap(51, 51, 51)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(buttonInserir)
														.addComponent(buttonLimpar))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(buttonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addContainerGap())
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 531, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 544, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		fieldCodigo.setText("" + ((PrevalentSystem)prevayler.prevalentSystem()).getNextCursoID());
		fieldCodigo.setEditable(false);
	}// </editor-fold>

	private void buttonHelpActionPerformed(java.awt.event.ActionEvent evt) {
		JanelaAjuda ajuda = new JanelaAjuda("Ajuda - Operação Inserir Curso", 
        		"-------------------------------------------------------------------------------------\n" +
        		"                              Operação Inserir Curso                                 \n" +
        		"-------------------------------------------------------------------------------------\n" +
        		"1. O número do campo código será o identificador do curso.                           \n" +
        		"2. Insira o nome do curso. É recomendável que o nome não seja repetido.              \n" +
        		"3. Marque o turno no qual o curso ocorre. O sistema permite apenas dois turnos.      \n" +
        		"4. Clique no botão Inserir.                                                          \n" +
        		"-------------------------------------------------------------------------------------\n" +
        		"Obs.: O turno marcado será aplicado a todas as classes pertencentes ao curso.        \n" +
        		"-------------------------------------------------------------------------------------\n");
        ajuda.setVisible(true);
	}

	private void buttonInserirActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Curso temp = (Curso) prevayler.execute(new CursoConsultaPorCodigoTransaction(Integer.parseInt(fieldCodigo.getText().trim())));
			if(temp == null) {
				prevayler.execute(makeCreateCursoTransaction());
				informationMessage("Curso cadastrado com sucesso.");
				buttonLimparActionPerformed(evt);
			}
			else {
				JOptionPane.showMessageDialog(PainelInserirCurso.this, "Já existe curso com esse código!", "Atenção", JOptionPane.WARNING_MESSAGE);
				buttonLimparActionPerformed(evt);
			}
		}
		catch(Exception exception) {
			exception.printStackTrace();
		}
	}

	private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {
		fieldCodigo.setText("" + ((PrevalentSystem)prevayler.prevalentSystem()).getNextCursoID());
		fieldNome.setText("");
		radioTurno1.setSelected(true);
	}


	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton buttonHelp;
	private javax.swing.JButton buttonInserir;
	private javax.swing.JButton buttonLimpar;
	private javax.swing.JTextField fieldCodigo;
	private javax.swing.JTextField fieldNome;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel labelCapacidade;
	private javax.swing.JLabel labelCodigo;
	private javax.swing.JLabel labelLogo;
	private javax.swing.JLabel labelNome;
	private javax.swing.JLabel labelTitulo;
	private javax.swing.JRadioButton radioTurno1;
	private javax.swing.JRadioButton radioTurno2;
	// End of variables declaration
	
	private Prevayler prevayler;
	
	private TransactionWithQuery makeCreateCursoTransaction() throws Exception {
		if(radioTurno1.isSelected()) {
			return (TransactionWithQuery) new CursoCreateTransaction(Integer.parseInt(fieldCodigo.getText().trim()),
					fieldNome.getText().trim(),
					1);
		}
		else {
			return (TransactionWithQuery) new CursoCreateTransaction(Integer.parseInt(fieldCodigo.getText().trim()),
					fieldNome.getText().trim(),
					2);
		}
		
	}

	private void informationMessage(String s) {
		message(s, "Ok!", JOptionPane.INFORMATION_MESSAGE);
	}

	private void message(String s, String title, int type) {
		JOptionPane.showMessageDialog(PainelInserirCurso.this, s, title, type);
	}

}
